"""
Generate_Report_Data.py
=======================
Compiles the static CSV output files into a single JavaScript file (data.js),
which acts as the static database for the Interactive Report web application.

Usage:
    python Generate_Report_Data.py

Outputs:
    Interactive_Report/data.js
"""

import os
import ast
import json
import pandas as pd

def generate_data_js():
    # 1. Store Locations
    locations_df = pd.read_csv('0_Fixed Data - Initial Setup data/WoolworthsLocations.csv')
    locations = {}
    for _, row in locations_df.iterrows():
        locations[row['Store']] = {'lat': row['Lat'], 'lng': row['Long']}
        
    # 2. Store Mean Demand
    demand_df = pd.read_csv('0_Non-FixedData-SimulationData/weekday_simulation_demand.csv', index_col='Store')
    mean_demand = demand_df.mean(axis=1).to_dict()

    # 3. Master Schedule (Truck Routes)
    master_df = pd.read_csv('Fixed Routes - Final/master_schedule.csv')
    master = []
    
    # Pre-calculate a color palette for regions
    region_colors = [
        '#388bfd', '#2ea043', '#f0c040', '#bc8cff', 
        '#ff7b72', '#79c0ff', '#56d364', '#e2e2e2'
    ]
    
    for i, row in master_df.iterrows():
        stores = ast.literal_eval(row['route'])
        master.append({
            'route_id': i,
            'stores': stores,
            'duration': row['duration'],
            'demand': row['demand'],
            'assigned_to': row['assigned_to'],
            'region': int(row['region']),
            'color': region_colors[int(row['region']) % 8] if row['assigned_to'] == 'WW' else '#e94560'
        })

    # 4. Shift Schedule (Gantt Data)
    shift_df = pd.read_csv('Fixed Routes - Final/shift_schedule.csv')
    shifts = []
    for _, row in shift_df.iterrows():
        route_stores = ast.literal_eval(row['route'])
        
        # Calculate start and end times in seconds since Midnight for animation
        # Shift 1 = 8am, Shift 2 = 2pm
        start_seconds = 8 * 3600 if row['shift'] == 1 else 14 * 3600
        end_seconds = start_seconds + row['duration_sec']
        
        shifts.append({
            'truck_id': row['truck_id'],
            'shift': row['shift'],
            'shift_time': row['shift_time'],
            'stores': route_stores,
            'duration_sec': row['duration_sec'],
            'overtime_sec': row['overtime_sec'],
            'region': int(row['region']),
            'color': region_colors[int(row['region']) % 8],
            'start_time': start_seconds,
            'end_time': end_seconds
        })
        
    # 5. Extract KPI Summary
    fleet_size = 24
    tk_cost = 75000
    if os.path.exists('Interactive_Report/params.json'):
        with open('Interactive_Report/params.json', 'r') as f:
            j = json.load(f)
            fleet_size = j.get('fleetSize', 24)
            tk_cost = j.get('truckCost', 75000)

    try:
        summary_df = pd.read_csv('Fixed Routes - Final/weekday_simulation_summary.csv')
        annual_sim_cost_row = summary_df[summary_df['metric'].str.contains('Expected annual cost', na=False)]
        annual_sim_cost = float(annual_sim_cost_row.iloc[0]['value']) if not annual_sim_cost_row.empty else 0.0
        sim_summary = summary_df.to_dict('records')
    except:
        annual_sim_cost = 0.0
        sim_summary = []

    total_annual_cost = (fleet_size * tk_cost) + annual_sim_cost
    kpis = {
        'fleet_size': fleet_size,
        'total_annual_cost': total_annual_cost,
        'stores_covered': len(locations) - 1,
        'sim_summary': sim_summary
    }

    # 5. Compile into Javascript
    js_content = f"""// AUTO-GENERATED BY Generate_Report_Data.py
// DO NOT EDIT DIRECTLY

window.REPORT_DATA = {{
    locations: {json.dumps(locations)},
    demand: {json.dumps(mean_demand)},
    master: {json.dumps(master)},
    shifts: {json.dumps(shifts)},
    kpis: {json.dumps(kpis)}
}};
"""
    
    out_path = 'Interactive_Report/data.js'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"  Generated {out_path} successfully.")

if __name__ == '__main__':
    generate_data_js()
