"""
Shift_Scheduler.py
==================
Phase 2: First-Fit Decreasing (FFD) Shift Scheduler.

Post-LP processing step. Takes the master schedule output from Global_LP.py
and assigns WW routes to physical truck shift slots (8am and 2pm).

Algorithm (First-Fit Decreasing):
1. Sort WW routes by duration (longest first).
2. For each route, assign it to the first truck/shift slot with remaining capacity.
3. Accept overtime (routes > 4 hours) with the overtime cost flagged — no route
   is rejected, as the LP already ensured feasibility.

This produces a concrete, executable schedule stating exactly which truck runs
which route at which time — suitable for presentation to management.

Usage:
    python Shift_Scheduler.py
    python Shift_Scheduler.py --fleet 20

Outputs:
    Fixed Routes - Final/shift_schedule.csv
    (and prints a human-readable schedule to stdout)
"""

import ast
import argparse
import pandas as pd

SHIFT_DURATION_SEC  = 14400   # 4 hours
OVERTIME_COST_SEC   = 325 / 3600
SHIFT_NAMES         = {1: '8:00 AM', 2: '2:00 PM'}


def build_shift_schedule(master_csv: str = 'Fixed Routes - Final/master_schedule.csv',
                         fleet_size: int = 24) -> pd.DataFrame:
    """
    Assign WW routes from the master schedule to physical truck/shift slots
    using the First-Fit Decreasing bin-packing heuristic.

    Parameters
    ----------
    master_csv : str
        Path to master_schedule.csv generated by Global_LP.py.
    fleet_size : int
        Number of WW trucks available.

    Returns
    -------
    pd.DataFrame
        Shift schedule with one row per route assignment.
    """
    master_df = pd.read_csv(master_csv)
    ww_routes = (
        master_df[master_df['assigned_to'] == 'WW']
        .copy()
        .sort_values('duration', ascending=False)   # FFD ordering
        .reset_index(drop=True)
    )

    print(f"\n  Scheduling {len(ww_routes)} WW routes "
          f"across {fleet_size} trucks (2 shifts each)...")

    # Each truck has 2 shift slots; track remaining capacity per slot
    # trucks[truck_id] = [remaining_shift1, remaining_shift2]
    trucks = {t: [SHIFT_DURATION_SEC, SHIFT_DURATION_SEC]
              for t in range(1, fleet_size + 1)}

    assignments = []
    unscheduled = []

    for _, route_row in ww_routes.iterrows():
        duration = route_row['duration']
        assigned = False

        for truck_id in sorted(trucks.keys()):
            for shift_idx in range(2):          # shift 1 then shift 2
                shift_num = shift_idx + 1
                remaining = trucks[truck_id][shift_idx]

                # Accept if it fits, or accept with overtime
                # (overtime can happen since LP allows routes > 4hr)
                if remaining > 0:               # slot is available
                    actual_used = min(duration, SHIFT_DURATION_SEC)
                    overtime_sec = max(0, duration - SHIFT_DURATION_SEC)
                    trucks[truck_id][shift_idx] = remaining - actual_used

                    assignments.append({
                        'truck_id':        truck_id,
                        'shift':           shift_num,
                        'shift_time':      SHIFT_NAMES[shift_num],
                        'route':           route_row['route'],
                        'duration_sec':    duration,
                        'duration_min':    round(duration / 60, 1),
                        'demand_pallets':  route_row['demand'],
                        'region':          route_row['region'],
                        'overtime_sec':    overtime_sec,
                        'overtime_cost':   round(overtime_sec * OVERTIME_COST_SEC, 2),
                    })
                    assigned = True
                    break
            if assigned:
                break

        if not assigned:
            # All slots full — this shouldn't happen if fleet_size >= LP solution
            unscheduled.append(route_row['route'])

    schedule_df = pd.DataFrame(assignments)

    # ------------------------------------------------------------------
    # Print human-readable schedule
    # ------------------------------------------------------------------
    print(f"\n  {'='*62}")
    print(f"  {'SHIFT SCHEDULE':^62}")
    print(f"  {'='*62}")

    for truck_id in sorted(schedule_df['truck_id'].unique()):
        truck_rows = schedule_df[schedule_df['truck_id'] == truck_id]
        print(f"\n  Truck {truck_id:>2}:")
        for _, r in truck_rows.iterrows():
            stores = ast.literal_eval(r['route'])
            store_str = ' → '.join(
                s.replace('Distribution Centre Auckland', 'DEPOT')
                 .replace('Woolworths ', 'WW ')
                 .replace('FreshChoice ', 'FC ')
                for s in stores
            )
            ot_str = f" [+{r['overtime_sec']/60:.0f}min OT]" if r['overtime_sec'] > 0 else ''
            print(f"    Shift {r['shift']} ({r['shift_time']}): "
                  f"{r['duration_min']}min | {r['demand_pallets']}pal | "
                  f"{store_str}{ot_str}")

    if unscheduled:
        print(f"\n  WARNING: {len(unscheduled)} routes could not be scheduled "
              f"(fleet too small for LP solution).")

    # ------------------------------------------------------------------
    # Summary stats
    # ------------------------------------------------------------------
    routes_scheduled = len(schedule_df)
    trucks_used = schedule_df['truck_id'].nunique()
    overtime_routes = (schedule_df['overtime_sec'] > 0).sum()
    total_overtime_cost = schedule_df['overtime_cost'].sum()
    double_shift_trucks = (
        schedule_df.groupby('truck_id')['shift'].nunique()
        .gt(1).sum()
    )

    print(f"\n  {'='*62}")
    print(f"  SCHEDULE SUMMARY")
    print(f"  {'='*62}")
    print(f"  Routes scheduled:          {routes_scheduled}")
    print(f"  Trucks used:               {trucks_used} / {fleet_size}")
    print(f"  Trucks on double-shift:    {double_shift_trucks}")
    print(f"  Routes with overtime:      {overtime_routes}")
    print(f"  Total overtime cost:       ${total_overtime_cost:,.2f}")
    print(f"  {'='*62}\n")

    return schedule_df


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Woolworths FFD Shift Scheduler')
    parser.add_argument('--fleet', type=int, default=24,
                        help='Number of WW trucks (default: 24)')
    parser.add_argument('--master', type=str,
                        default='Fixed Routes - Final/master_schedule.csv',
                        help='Path to master_schedule.csv')
    args = parser.parse_args()

    import os
    import json
    
    params_path = os.path.join('Interactive_Report', 'params.json')
    if os.path.exists(params_path):
        with open(params_path, 'r') as f:
            j = json.load(f)
            if args.fleet == 24:
                args.fleet = j.get('fleetSize', args.fleet)
            
            # Override globals dynamically
            OVERTIME_COST_SEC = j.get('otRate', 325) / 3600

    if not os.path.exists(args.master):
        print(f"  Master schedule not found at '{args.master}'.")
        print("  Run Global_LP.py first to generate the master schedule.")
        exit(1)

    schedule_df = build_shift_schedule(
        master_csv=args.master,
        fleet_size=args.fleet,
    )

    output_path = 'Fixed Routes - Final/shift_schedule.csv'
    schedule_df.to_csv(output_path, index=False, quoting=1)
    print(f"  Shift schedule saved to: {output_path}")
